# Exported from Render on 2026-05-15T21:56:26Z
version: "1"
services:
- type: web
  name: school_project-1
  runtime: python
  repo: https://github.com/J-ohnP-aul/school_project
  plan: free
  region: virginia
  buildCommand: poetry install && python manage.py collectstatic --no-input
  startCommand: gunicorn config.wsgi:application
  autoDeployTrigger: commit
