# Generated by Django 6.0.5 on 2026-05-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_gradelevel_subject_term'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gaurdian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gaurdian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=30),
        ),
        # Data migration: convert existing text grade values into GradeLevel rows
        # and replace the stored text with the corresponding GradeLevel id so
        # the subsequent AlterField to a ForeignKey succeeds.
        migrations.RunPython(
            code=lambda apps, schema_editor: (
                (lambda StudentProfile, GradeLevel, db_alias: (
                    [
                        GradeLevel.objects.using(db_alias).get_or_create(name=name)
                        for name in set(x[0] for x in StudentProfile.objects.using(db_alias).values_list('grade') if x[0])
                    ],
                    [
                        StudentProfile.objects.using(db_alias).filter(pk=sp.pk).update(grade=str(GradeLevel.objects.using(db_alias).get(name=sp.grade).pk))
                        for sp in StudentProfile.objects.using(db_alias).all()
                        if sp.grade
                    ]
                ))(
                    apps.get_model('accounts', 'StudentProfile'),
                    apps.get_model('academics', 'GradeLevel'),
                    schema_editor.connection.alias
                )
            ),
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.gradelevel'),
        ),
    ]
