# Generated by Django 6.0.5 on 2026-05-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_gaurdian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(max_length=50),
        ),
    ]
