# Generated by Django 6.0.5 on 2026-05-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_studentprofile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='gaurdian_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gaurdian_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='stream',
        ),
    ]
