# Generated by Django 6.0.5 on 2026-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_studentprofile_gaurdian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(default='Temporary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(default='Temporary', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
