# Generated by Django 6.0.5 on 2026-05-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
