# Generated by Django 6.0.5 on 2026-05-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_competency_assesment'),
        ('accounts', '0005_studentprofile_guardian_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assesment',
            new_name='Assessment',
        ),
        migrations.CreateModel(
            name='DraftAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('stream', models.CharField(blank=True, max_length=30)),
                ('draft_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.competency')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
