# Generated by Django 6.0.5 on 2026-05-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_assesment_assessment_draftassessment'),
        ('accounts', '0005_studentprofile_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftassessment',
            name='draft_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='draftassessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_drafts', to='accounts.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='draftassessment',
            unique_together={('teacher', 'grade', 'stream', 'subject', 'competency', 'term')},
        ),
    ]
